package:
  name: matplotlib
  version: "2.2.0"

source:
  fn: matplotlib-2.2.0.tar.gz
  url: https://pypi.python.org/packages/51/15/a397b941318d7d7f9cf2acbb4a35ce53681ec9799068f5ea57d91a6eea7e/matplotlib-2.2.0.tar.gz
  md5: 0d12cadce629e8175dbace92cb71d136
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - matplotlib = matplotlib:main
    #
    # Would create an entry point called matplotlib that calls matplotlib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7.1
    - cycler >=0.10
    - pyparsing >=2.0.1,!=2.0.4,!=2.1.2,!=2.1.6
    - python-dateutil >=2.1
    - pytz
    - six >=1.10
    - kiwisolver >=1.0.1
    - pkg-config
    
  run:
    - python
    - numpy >=1.7.1
    - cycler >=0.10
    - pyparsing >=2.0.1,!=2.0.4,!=2.1.2,!=2.1.6
    - python-dateutil >=2.1
    - pytz
    - six >=1.10
    - kiwisolver >=1.0.1
    - pkg-config
    - libpng-devel
    - pkg-config
    

test:
  # Python imports
  imports:
    - matplotlib
    - matplotlib.axes
    - matplotlib.backends
    - matplotlib.backends.qt_editor
    - matplotlib.cbook
    - matplotlib.compat
    - matplotlib.projections
    - matplotlib.sphinxext
    - matplotlib.style
    - matplotlib.testing
    - matplotlib.testing._nose
    - matplotlib.testing._nose.plugins
    - matplotlib.testing.jpl_units
    - matplotlib.tri
    - mpl_toolkits
    - mpl_toolkits.axes_grid
    - mpl_toolkits.axes_grid1
    - mpl_toolkits.axisartist
    - mpl_toolkits.mplot3d

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://matplotlib.org
  license: Python Software Foundation License
  summary: 'Python plotting package'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
